# Generated by Django 3.1 on 2020-10-10 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enrolments',
            field=models.ManyToManyField(related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
