# Generated by Django 3.1 on 2020-10-10 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_contest_enrolments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='subs',
            field=models.ManyToManyField(related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
