# Generated by Django 3.1 on 2020-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_contest_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='timelimit',
            field=models.IntegerField(),
        ),
    ]
