# Generated by Django 3.1 on 2020-10-10 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20201010_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='enrolments',
            field=models.ManyToManyField(default=None, null=True, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='subs',
            field=models.ManyToManyField(default=None, null=True, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
