# Generated by Django 3.1 on 2020-10-10 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_auto_20201010_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='enrolments',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='subs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
