# Generated by Django 4.2.6 on 2023-10-05 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20201010_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='enrolments',
            field=models.ManyToManyField(blank=True, default=None, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='subs',
            field=models.ManyToManyField(blank=True, default=None, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
