# Generated by Django 4.2.6 on 2023-10-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_alter_contest_enrolments_alter_contest_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='userSubmision',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='TypingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('contestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.contest')),
            ],
        ),
    ]
