# Generated by Django 4.2.6 on 2023-10-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_submissions_usersubmision_typingtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='userSubmision',
            field=models.TextField(default=''),
        ),
    ]
