# Generated by Django 4.2.6 on 2023-10-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_contest_contesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='timeTaken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissions',
            name='wordsPerMin',
            field=models.IntegerField(default=0),
        ),
    ]
