# Generated by Django 4.2.6 on 2023-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_submissions_timetaken_submissions_wordspermin'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='backspaceCount',
            field=models.IntegerField(default=0),
        ),
    ]
