# Generated by Django 4.2.6 on 2023-10-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0014_remove_submissions_wordspermin_submissions_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='gwpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='nwpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
