# Generated by Django 4.2.6 on 2023-10-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_alter_submissions_accuracy_alter_submissions_gwpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
